[package]
name = "choreograph"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
indexmap = "2.7"
itertools = "0.14"
derive-where = "1.2"

[dev-dependencies]
tokio = { version = "1.43", features = ["rt", "macros"] }
